2022-05-20 09:01:12.075104: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2022-05-20 09:01:18.530556: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2022-05-20 09:01:18.902858: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:1a:00.0 name: Quadro RTX 8000 computeCapability: 7.5
coreClock: 1.77GHz coreCount: 72 deviceMemorySize: 47.43GiB deviceMemoryBandwidth: 625.94GiB/s
2022-05-20 09:01:18.902912: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2022-05-20 09:01:18.939106: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2022-05-20 09:01:18.954471: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2022-05-20 09:01:18.964065: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2022-05-20 09:01:18.997895: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2022-05-20 09:01:19.011159: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2022-05-20 09:01:19.101746: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2022-05-20 09:01:19.112339: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2022-05-20 09:01:19.119055: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-20 09:01:19.131942: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2200000000 Hz
2022-05-20 09:01:19.132121: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x556e45672100 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-05-20 09:01:19.132143: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2022-05-20 09:01:19.417838: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x556e45685b70 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2022-05-20 09:01:19.417879: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Quadro RTX 8000, Compute Capability 7.5
2022-05-20 09:01:19.423668: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:1a:00.0 name: Quadro RTX 8000 computeCapability: 7.5
coreClock: 1.77GHz coreCount: 72 deviceMemorySize: 47.43GiB deviceMemoryBandwidth: 625.94GiB/s
2022-05-20 09:01:19.423719: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2022-05-20 09:01:19.423746: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2022-05-20 09:01:19.423756: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2022-05-20 09:01:19.423765: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2022-05-20 09:01:19.423774: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2022-05-20 09:01:19.423782: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2022-05-20 09:01:19.423792: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2022-05-20 09:01:19.434025: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2022-05-20 09:01:19.434188: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2022-05-20 09:01:20.494592: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-05-20 09:01:20.494645: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2022-05-20 09:01:20.494652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2022-05-20 09:01:20.504213: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 45360 MB memory) -> physical GPU (device: 0, name: Quadro RTX 8000, pci bus id: 0000:1a:00.0, compute capability: 7.5)
2022-05-20 09:03:00.387135: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:581] layout failed: Invalid argument: Size of values 0 does not match size of permutation 4 @ fanin shape inSelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer
2022-05-20 09:03:02.365100: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2022-05-20 09:03:02.880137: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2022-05-20 09:03:06.352779: W tensorflow/stream_executor/gpu/asm_compiler.cc:81] Running ptxas --version returned 256
2022-05-20 09:03:07.669055: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: ptxas exited with non-zero error code 256, output: 
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.
2022-05-20 09:03:24.539639: I tensorflow/core/kernels/cuda_solvers.cc:180] Creating CudaSolver handles for stream 0x556e45701d00
2022-05-20 09:03:24.540581: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2022-05-20 09:03:25.985482: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
/home4/jpmeneses/IDEAL-GAN/module.py:621: RuntimeWarning: divide by zero encountered in double_scalars
  true_fn=lambda: self._initial_learning_rate * (1 - 1 / (self._steps - self._step_decay) * (step - self._step_decay)),
-----------------------------------------
keras-unet init: TF version is >= 2.0.0 - using `tf.keras` instead of `Keras`
-----------------------------------------
Num. Elements- DS1: 512
Num. Elements- DS2: 384
Num. Elements- DS3: 1341
Num. Elements- DS4: 1308
Num. Elements- DS5: 701
Acquisition Dimensions: 192 192
Echoes: 6
Output Maps: 6
Training input shape: (3180, 192, 192, 12)
Training output shape: (3180, 192, 192, 6)
Validation input shape: (384, 192, 192, 12)
Validation output shape: (384, 192, 192, 6)
Testing input shape: (682, 192, 192, 12)
Testing output shape: (682, 192, 192, 6)
No checkpoint specified (save_path=None); nothing is being restored.
Traceback (most recent call last):
  File "train-IDEAL.py", line 695, in <module>
    A2B, B2A, A2B2A, B2A2B, val_loss_dict = validation_step(A, B, TE_valid)
  File "train-IDEAL.py", line 595, in validation_step
    A2B, B2A, A2B2A, B2A2B, val_loss_dict = sample(A, B, TE)
  File "/home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 696, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3065, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    train-IDEAL.py:587 sample  *
        B2A2B_WF = wf.get_rho(B2A,B2A2B_PM,te=te_B)
    /home4/jpmeneses/IDEAL-GAN/wflib/IDEAL_model.py:321 get_rho  *
        Smtx = tf.transpose(tf.reshape(S, [n_batch, num_voxel, ne]), perm=[0,2,1])
    /home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    /home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py:195 reshape
        result = gen_array_ops.reshape(tensor, shape, name)
    /home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py:8233 reshape
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py:742 _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    /home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py:591 _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    /home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:3477 _create_op_internal
        ret = Operation(
    /home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:1974 __init__
        self._c_op = _create_c_op(self._graph, node_def, inputs,
    /home1/jpmeneses/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:1815 _create_c_op
        raise ValueError(str(e))

    ValueError: Cannot reshape a tensor with 221184 elements to shape [1,36864,1] (36864 elements) for '{{node Reshape_14}} = Reshape[T=DT_COMPLEX64, Tshape=DT_INT32](Complex_7, Reshape_14/shape)' with input shapes: [1,192,192,6], [3] and with input tensors computed as partial shapes: input[1] = [1,36864,1].

